graph_server: graph_server.cpp ./graph/graph.cpp ./graph/graph.h ./library/mongoose.c ./library/mongoose.h ./library/virtual_memory.hpp
	g++ -std=c++11 -o cs426_graph_server graph_server.cpp ./graph/graph.cpp ./library/mongoose.c ./library/virtual_memory.cpp -I.
